import { Student } from "../../models/student";

export const initStudent: Student = {
  id: 0,
  studentCode: "",
  name: "",
  dateOfBirth: "",
  className: "",
  gender: "",
  address: "",
  phone: "",
};

const rows = [
  {
    class: "6A1",
    quantity: 40,
    numberPresent: 38,
    absenceWithPermission: 1,
    absenceWithoutPermission: 1,
    late: 10,
  },
  {
    class: "6A2",
    quantity: 70,
    numberPresent: 60,
    absenceWithPermission: 5,
    absenceWithoutPermission: 5,
    late: 10,
  },
  {
    class: "6A3",
    quantity: 70,
    numberPresent: 60,
    absenceWithPermission: 5,
    absenceWithoutPermission: 5,
    late: 10,
  },
  {
    class: "7A1",
    quantity: 70,
    numberPresent: 60,
    absenceWithPermission: 5,
    absenceWithoutPermission: 5,
    late: 10,
  },
  {
    class: "7A2",
    quantity: 70,
    numberPresent: 60,
    absenceWithPermission: 5,
    absenceWithoutPermission: 5,
    late: 10,
  },
  {
    class: "7A3",
    quantity: 70,
    numberPresent: 60,
    absenceWithPermission: 5,
    absenceWithoutPermission: 5,
    late: 10,
  },
  {
    class: "7A4",
    quantity: 70,
    numberPresent: 60,
    absenceWithPermission: 5,
    absenceWithoutPermission: 5,
    late: 10,
  },
  {
    class: "8A1",
    quantity: 70,
    numberPresent: 60,
    absenceWithPermission: 5,
    absenceWithoutPermission: 5,
    late: 10,
  },
  {
    class: "8A2",
    quantity: 70,
    numberPresent: 60,
    absenceWithPermission: 5,
    absenceWithoutPermission: 5,
    late: 10,
  },
  {
    class: "8A3",
    quantity: 70,
    numberPresent: 60,
    absenceWithPermission: 5,
    absenceWithoutPermission: 5,
    late: 10,
  },
  {
    class: "9A1",
    quantity: 70,
    numberPresent: 60,
    absenceWithPermission: 5,
    absenceWithoutPermission: 5,
    late: 10,
  },
  {
    class: "9A2",
    quantity: 70,
    numberPresent: 60,
    absenceWithPermission: 5,
    absenceWithoutPermission: 5,
    late: 10,
  },
  {
    class: "6A",
    quantity: 70,
    numberPresent: 60,
    absenceWithPermission: 5,
    absenceWithoutPermission: 5,
    late: 10,
  },
  {
    class: "9A3",
    quantity: 70,
    numberPresent: 60,
    absenceWithPermission: 5,
    absenceWithoutPermission: 5,
    late: 10,
  },
  {
    class: "9A4",
    quantity: 70,
    numberPresent: 60,
    absenceWithPermission: 5,
    absenceWithoutPermission: 5,
    late: 10,
  },
  {
    class: "6A",
    quantity: 70,
    numberPresent: 60,
    absenceWithPermission: 5,
    absenceWithoutPermission: 5,
    late: 10,
  },
  {
    class: "6A",
    quantity: 70,
    numberPresent: 60,
    absenceWithPermission: 5,
    absenceWithoutPermission: 5,
    late: 10,
  },
];

const initialState = {
  data: rows,
  isLoading: false,
  errorMessage: null,
};

export default initialState;
